# -*- coding: utf-8 -*-
"""finite_difference

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ge6B65N4tAHagywgpOUPU13BMqgPB2Ke
"""

import numpy as np

def solve_fd(u0, v0, nu = 0.01, T = 0.5, Nx = 50, Ny = 50):
  """
  This is my solver for 2D Burgers equation.

  u0, v0 are initial veloicity fields

  nu is the viscocity

  T is the final time
  """

  u = u0.copy()
  v = v0.copy()

  dx = 1 / (Nx - 1)
  dy = 1 / (Ny - 1)

  max_u = np.max(np.abs(u))
  max_v = np.max(np.abs(v))

  dt_conv = min(dx / max_u, dy / max_v)
  dt_diff = min(dx**2, dy**2) / (4 * nu)
  dt = 0.2 * min(dt_conv, dt_diff)

  Nt = int(T / dt)

  for _ in range(Nt):
    u_x = np.gradient(u, dx, axis = 1)
    u_y = np.gradient(u, dy, axis = 0)
    v_x = np.gradient(v, dx, axis = 1)
    v_y = np.gradient(v, dy, axis = 0)

    u_xx = np.gradient(u_x, dx, axis = 1)
    u_yy = np.gradient(u_y, dy, axis = 0)
    v_xx = np.gradient(v_x, dx, axis = 1)
    v_yy = np.gradient(v_y, dy, axis = 0)

    u = u + dt * (-(u * u_x + v * u_y) + nu * (u_xx * u_yy))
    v = v + dt * (-(u * v_x + v * v_y) + nu * (v_xx * v_yy))

  return u, v