# -*- coding: utf-8 -*-
"""PINN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S-oZ0CkB6bgtiFqggrtUprCOl-jRzpgW
"""

import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt


class PINN(nn.Module):
  def __init__(self):

    super().__init__()
    self.net = nn.Sequential(
        nn.Linear(3, 25),
        nn.Tanh(),
        nn.Linear(25, 25),
        nn.Tanh(),
        nn.Linear(25, 25),
        nn.Tanh(),
        nn.Linear(25, 2)
    )

  def forward(self, x):

    return self.net(x)

def solve_PINN(u0, v0, epochs = 10000, nu = 0.01):

  model = PINN()
  optimizer = torch.optim.Adam(model.parameters(), lr = 1e-3)

  u0 = torch.tensor(u0.flatten(), dtype = torch.float32).view(-1, 1)
  v0 = torch.tensor(v0.flatten(), dtype = torch.float32).view(-1, 1)

  NyNx = u0.shape[0] * u0.shape[1]
  Nx = int(np.sqrt(NyNx))
  Ny = Nx

  x = np.linspace(0,1,Nx)
  y = np.linspace(0,1,Ny)
  Xg, Yg = np.meshgrid(x,y)

  x = torch.tensor(Xg.flatten(), dtype=torch.float32).view(-1,1)
  y = torch.tensor(Yg.flatten(), dtype=torch.float32).view(-1,1)
  t = torch.zeros_like(x)
  X = torch.cat([x, y, t], dim = 1)

  for _ in range(epochs):

    optimizer.zero_grad()
    pre = model(X)

    loss = ((pre[:, 0:1] - u0)**2).mean() + ((pre[:, 1:2] - v0)**2).mean()
    loss.backward()
    optimizer.step()

  return model

Nx, Ny = 50, 50
x = np.linspace(0,1,Nx)
y = np.linspace(0,1,Ny)
X, Y = np.meshgrid(x,y)

a1, a2 = 0.5, 0.8
b1, b2 = 0.3, 0.6

u0 = 0.2 * a1 * np.sin(np.pi * X) + a2 * np.cos(2 * np.pi * Y)
v0 = 0.2 * b1 * np.sin(2 * np.pi * X) + b2 * np.cos(np.pi * Y)

model = solve_PINN(u0, v0)

# flatten for model input
x_t = torch.tensor(X.flatten(), dtype=torch.float32).view(-1,1)
y_t = torch.tensor(Y.flatten(), dtype=torch.float32).view(-1,1)
t_t = torch.zeros_like(x_t)

X_input = torch.cat([x_t, y_t, t_t], dim=1)

# evaluate model
model.eval()
with torch.no_grad():
    pre = model(X_input)

u_pinn = pre[:,0].reshape(Ny, Nx).numpy()
v_pinn = pre[:,1].reshape(Ny, Nx).numpy()
plt.contourf(X, Y, u0)
plt.figure()
plt.title("u(x,y) - PINN")
plt.imshow(u_pinn, extent=[0,1,0,1], origin='lower')
plt.colorbar()
plt.show()